---

- hosts: all
  become: true
  tasks:

    - name: install apache,htop and update repository index
      package:
        name:
          - "{{ apache_package }}"
          - htop
        state: latest
        update_cache: true
