---

- hosts: all
  become: true
  pre_tasks:
    
    - name: update packages and repo index
      dnf:
        update_only: yes
        update_cache: yes



- hosts: web_servers
  become: true
  tasks:

    - name: install apache2,htop and update repository indexes
      apt:
        name:
          - apache2
          - htop
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install httpd,htop and update repository indexes
      dnf:
        name:
          - httpd
          - htop
        state: latest
      when: ansible_distribution == "RedHat"
