---

- hosts: all
  become: true
  pre_tasks:
    
    - name: update packages and repo index
      tags: always
      dnf:
        update_only: yes
        update_cache: yes



- hosts: web_servers
  become: true
  tasks:

    - name: install apache2,htop and update repository indexes
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2
          - htop
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install httpd,htop and update repository indexes
      tags: httpd,redhat
      dnf:
        name:
          - httpd
          - htop
        state: latest
      when: ansible_distribution == "RedHat"

    - name: start and enable httpd
      tags: httpd,apache,redhat
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "RedHat"

    - name: edit the mail id of server admin
      tags: apache,httpd,apache2
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin rushi.vt@gmail.com
      when: ansible_distribution == "RedHat"
      register: httpd

    - name: restart HTTPD
      tags: httpd,apache,redhat
      service:
        name: httpd
        state: restarted
      when: httpd.changed

    - name: copy webpage from host to guest
      tags: apache,httpd,apache2
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
      when: ansible_distribution == "RedHat"


- hosts: web_servers
  become: true
  tasks:

    - name: installing unzip
      tags: unzip
      package:
        name: unzip
        state: latest


    - name: installing terraform
      tags: terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_arm64.zip
        dest: /usr/local/bin
        remote_src: yes
        owner: root
        group: root
        mode: 0755

